/*
 * Copyright (c) 2018 Abex
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
namespace OSRSCache.util
{
//
// 	public class IDClass : PrintWriter
// 	{
// 		private readonly Namer namer = new Namer();
//
// //JAVA TO C# CONVERTER WARNING: Method 'throws' clauses are not available in C#:
// //ORIGINAL LINE: private IDClass(java.io.File file) throws java.io.FileNotFoundException
// 		private IDClass(File file) : base(file)
// 		{
// 		}
//
// //JAVA TO C# CONVERTER WARNING: Method 'throws' clauses are not available in C#:
// //ORIGINAL LINE: public static IDClass create(java.io.File directory, String name) throws java.io.IOException
// 		public static IDClass create(File directory, string name)
// 		{
// 			IDClass c = new IDClass(new File(directory, name + ".java"));
// 			c.println("/* This file is automatically generated. Do not edit. */");
// 			c.println("package net.runelite.api;");
// 			c.println();
// 			c.print("public final class ");
// 			c.println(name);
// 			c.println("{");
// 			return c;
// 		}
//
// 		public virtual void add(string name, int id)
// 		{
// 			string javaName = namer.name(name, id);
// 			if (string.ReferenceEquals(javaName, null))
// 			{
// 				return;
// 			}
//
// 			println("	public static final int " + javaName + " = " + id + ";");
// 		}
//
// 		public override void println()
// 		{
// 			// Java 9+ only reads line.separator on startup, so we have to override it here
// 			write('\n');
// 		}
//
// 		public override void close()
// 		{
// 			println("\t/* This file is automatically generated. Do not edit. */");
// 			println("}");
// 			base.close();
// 		}
// 	}

}